### ISSUE TITLE
Add commitment-level data to project detail panel

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-cp-map#17]
Add timeline and commitment-level data to project detail panel.

- [x] Add commitment data to project detail panel according to designs ([desktop](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1194-22664&m=dev) and [mobile](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1337-20505&m=dev))
- [x] Includes adding timeline and commitments table

Blocked by #51

**Comment by TangoYankee** [comment]
Blocked by #18

**Comment by TangoYankee** [comment]
@TylerMatteo We'll need to update the API to get the description for the capital commitment. We're only returning the four letter code of the commitment type. We'll need the text of the commitment type. It is used to fill out the "description" field. There are three options.

1) Create an endpoint specifically to lookup the text from the code, similar to land-uses
2) Add a field to the existing "capital commitments" endpoint
3) Replace the existing "type" field with the text, instead of the code

My preference is for option 1.
- Option 2 returns "repeat" or "redundant" data.
- Option 3 is a breaking change.
- Both options 2 and 3 will require a JOIN.

Option 1 sends the data once without requiring a join on the capital-commitments query.

**Comment by horatiorosa** [comment]
I say we go with option 2. The `capital_commitment_type` table only has 13 rows. I don't think that getting a little repeat/redundant data really be that bad,

**Comment by TangoYankee** [comment]
> I say we go with option 2. The `capital_commitment_type` table only has 13 rows. I don't think that getting a little repeat/redundant data really be that bad,

It's less a matter of how many commitment types there are and more about how many times we send the same data. For example, if a project has a few dozen commitments associated with it and they're all type "Construction", we're sending that description a few dozen times. Option 1 sends the description once and then the commitment can use its "type" code to look up the full text in the returned map.

**Comment by TangoYankee** [comment]
A draft PR implementing option 1: NYCPlanning/ae-zoning-api#361

**Comment by TylerMatteo** [comment]
Hey @wndyli @jessicashanshanhuang - @TangoYankee noticed that the designs for commitment data use an "extra small" font size with size 10px in a few places. The design system tokens Jasmine left behind only went down to "small" at 14px. I'm pretty sure that was an intentional decision because fonts below that are an accessibility concern. Do WCAG standards specify font size standards for accessibility?

We could just go with 10 (or 12) and assume users who need to will enlarge the text in their browser, but we'll have to make sure that doesn't break other parts of our implementation.

**Comment by jessicashanshanhuang** [comment]
Hello @TylerMatteo, @TangoYankee! There is no specific WCAG standards specifying font size for accessibility, however, we can see how 10px would be too small. Looking into some [accessibility checkers](https://www.getstark.co/support/getting-started/using-typography/#main) and other [design systems like USWDS](https://designsystem.digital.gov/components/typography/#line-height-2), it seems like 12px should be the smallest we should go. 

Also is CPP complying to AA standards? I saw [this statement](https://www.nyc.gov/site/planning/about/accessibility.page) and it seems most products are semi-AA compliant? I know there was a recent update to aim for AAA in other sectors of DCP so just wanted to note that down if that is something that will come up in the future. 

We'll also note this observation down and update the typography guidelines in the new design system so we have a point of reference 🫡 - thanks for pointing this out!

**Comment by TangoYankee** [comment]
@jessicashanshanhuang thank you for looking into the standards and checkers. 

I was looking at the Chakra Typography documentation. The documentation doesn't seem to mention the literal value of the `xs` token. However, the webpage inspector reveals it is 0.75rem (default 12px).

Also, I have a draft implementation that uses 0.75rem (default to 12px) in place of 10px and I think it still works well. (Ignore the button. We still need to make an `xs` button)

![Screenshot from 2024-08-07 10-05-09](https://github.com/user-attachments/assets/e4b43ec0-0b57-434b-a1a9-c2e7c5bf1bbc)

**Comment by TangoYankee** [comment]
Ahh yes, should probably communicate what I am up to:

https://github.com/NYCPlanning/ae-streetscape/issues/65 and https://github.com/NYCPlanning/ae-streetscape/issues/64 (for the table components)

**Comment by jessicashanshanhuang** [comment]
> I was looking at the Chakra Typography documentation. The documentation doesn't seem to mention the literal value of the `xs` token. However, the webpage inspector reveals it is 0.75rem (default 12px).
> 
> Also, I have a draft implementation that uses 0.75rem (default to 12px) in place of 10px and I think it still works well. (Ignore the button. We still need to make an `xs` button)
> 
> ![Screenshot from 2024-08-07 10-05-09](https://private-user-images.githubusercontent.com/11068062/355854048-e4b43ec0-0b57-434b-a1a9-c2e7c5bf1bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDQ1MjEsIm5iZiI6MTcyMzA0NDIyMSwicGF0aCI6Ii8xMTA2ODA2Mi8zNTU4NTQwNDgtZTRiNDNlYzAtMGI1Ny00MzRiLWExYTktYzJlN2M1YmYxYmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZDQ4OTVhMjcxMDBiZGFjNDI1ZDZkYjhlZjIyMDJkOTU1N2U1ODQ5NDhjNDUzZjhmMDRkODBjMWIzNTIxODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYoA1lWslw4i2krkg1K_Qdn4qMHtDbgkojyrJtnwcIU)

@TangoYankee Looks good! I was looked into the [Chakra Theme doc](https://arc.net/l/quote/blpjyugu) and it does confirm `xs` is 12px:
> `fontSizes: {
    xs: "12px",
    sm: "14px",
    md: "16px",
    lg: "18px",
    xl: "20px",
    "2xl": "24px",
    "3xl": "28px",
    "4xl": "36px",
    "5xl": "48px",
    "6xl": "64px",
  },`
  
Also would it be possible to round the corners the table? It's not a high priority but would help align the look of the other elements since their borders are rounded.

**Comment by TangoYankee** [comment]
> Also would it be possible to round the corners the table?

Yup!

I'll also try to get these changes into QA in time for a full design review

**Comment by TangoYankee** [comment]
@jessicashanshanhuang QA has these changes now.

This branch includes:
1) updates to the capital project details to match the latest designs 
2) the addition of the commitments timeline
     - For the commitments timeline, not every projects has commitments in the future or past. In these cases, I don't display a year. Let me know whether this makes sense. 
3) addition of the commitments table

Here is a quick link to an example project. But of course, you can click around to different projects to see how the panel reacts to different data combinations.
https://qa-capitalplanning.nycplanningdigital.com/capital-projects/846/P-311WATT

**Comment by TangoYankee** [comment]
Feedback:
[Timeline expands too large](https://github.com/NYCPlanning/ae-streetscape/issues/65#issuecomment-2276192253)

I updated the timeline to have a maximum width of 300px and to center itself when it no longer fills the screen. Let me know what you think @jessicashanshanhuang

**Comment by jessicashanshanhuang** [comment]
@TangoYankee I'll put the rest of the feedback here to keep the point of reference in this convo:

Related to the [Timeline comment](https://github.com/NYCPlanning/ae-streetscape/issues/65#issuecomment-2276192253), centering was a good choice! If we could bump up the max width to 350px, that portion would be good to go. The reason to bump up the width is to help balance the timeline's prominence since there is decent amount of negative space. 

For [the table component](https://github.com/NYCPlanning/ae-streetscape/issues/64), @wndyli pointed out the all caps for description content does impact readability and we were wondering if that could be changed? I'm assuming that's more related to where the data is being drawn. 

Additionally, padding could be added to the top to center commitment details and button for alignment. 

![Screenshot 2024-08-08 at 10 01 41 AM](https://github.com/user-attachments/assets/af3af498-ba5e-4c8f-8103-056f0df3962e)

I noticed there is no background for the table when it switch over from desktop view and the scrollbar next to the timeline card is not working. It does bring up the discussion if we should include a scrollbar for that view in case a user is not on a tablet but a smaller pc device. 

![Screenshot 2024-08-08 at 10 08 36 AM](https://github.com/user-attachments/assets/2e0ff7ff-590f-43dc-810b-b10ec13797fe)

**Comment by TangoYankee** [comment]
I'll update the timeline max width to 350px and add the background to the commitments table on mobile.

For the scrollbar, that was a mistake in the "overflow" setting. We shouldn't need one- "limiting the height"/"placing the scroll" on the commitments table should mean there is always enough space for the timeline without needing to add a scrollbar. I'll remove it.

**Comment by TangoYankee** [comment]
Updated with those changes. I also integrated the Filter Menu restyle into this branch. So, it's possible to see how the capital project panel interacts with the filter menu
